# Generated by Django 4.0.6 on 2022-07-05 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.TextField()),
                ('options_one', models.CharField(max_length=120)),
                ('options_two', models.CharField(max_length=120)),
                ('options_three', models.CharField(max_length=120)),
                ('options_four', models.CharField(max_length=120)),
                ('counting_for_opt_one', models.IntegerField(default=0)),
                ('counting_for_opt_two', models.IntegerField(default=0)),
                ('counting_for_opt_three', models.IntegerField(default=0)),
                ('counting_for_opt_four', models.IntegerField(default=0)),
            ],
        ),
    ]
