# Generated by Django 4.0.6 on 2022-07-05 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_poll_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Poll',
        ),
    ]
